name: tip_employee
description: "A new Flutter project."
publish_to: 'none' # Private project, not published to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=3.8.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_fonts: ^6.3.0
  flutter_svg: ^2.0.9
  image_picker: ^0.8.7+4
  fl_chart: ^0.69.0
  flutter_bloc: ^9.1.1
  bloc: ^9.0.0
  json_annotation: ^4.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.5.0
  json_serializable: ^6.6.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
targets:
  $default:
    builders:
      json_serializable:
        options:
          field_rename: snake
          checked: true